
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compilador_esencial;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCR = 8;
  public static final int DISTINTOCERO = 3;
  public static final int DECR = 7;
  public static final int FIN = 5;
  public static final int EOF = 0;
  public static final int NUMERO = 11;
  public static final int ID = 10;
  public static final int IGUAL = 9;
  public static final int error = 1;
  public static final int MIENTRAS = 2;
  public static final int HACER = 4;
  public static final int PUNTOYCOMA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MIENTRAS",
  "DISTINTOCERO",
  "HACER",
  "FIN",
  "PUNTOYCOMA",
  "DECR",
  "INCR",
  "IGUAL",
  "ID",
  "NUMERO"
  };
}

